### PR TITLE
1326 hide breadcrumb divider element

### LINKED ISSUE #1326: A11y Code Sprint Berlin: Success Criterion 9.4.1.2 Name, Role, Value - aria-current in Breadcrumb
**Page**
-
Breadcrumb

**Description**
-
For all user interface components (including but not limited to: form elements, links and components generated by scripts), the name and role can be programmatically determined; states, properties, and values that can be set by the user can be programmatically set; and notification of changes to these items is available to user agents, including assistive technologies.
[To WCAG](https://www.w3.org/TR/WCAG21/#name-role-value)

**Solution**
-
1. Slashes (see screenshot) in breadcrumb have to be hidden with `aria-hidden=true`.
2. `aria-current` is only allowed to be used for the actually selected page. In our case, aria-current is read aloud by the screenreader for the two sites (see red border in screenshot). Please set it on the last word "Abstract" in the breadcrumb.

**Context, links and screenshots**
-
Breadcrumb-aria-current-slashes-2023-06-01 22_20_31-Abstract

### PR DESCRIPTION
**Pull request by alboth**
# Pull Request

## Related Issues

* Fixes #1326

## Prerequisites

* [x] Changes have been tested on TYPO3 v12.5 LTS
* [x ] Changes have been tested on PHP 8.1

## Description

Override Bootstrap SCSS in order to prevent ::before element from beeing read in the screen reader. 

code infos here: https://a11ysupport.io/tests/tech__css__css_generated_content_alt

## Steps to Validate

1. build frontend
2. check if ::before element is using the news syntax "/" / ""

### CODE REVIEW

**Comment by linawolf** [comment]
@alboth please see https://github.com/benjaminkott/bootstrap_package/pull/1341/files on how to build the frontend files

**Comment by alboth** [comment]
@linawolf review ready ... merge request sent

**Comment by alboth** [comment]
@linawolf review ready ... merge request sent

**Comment by benjaminkott** [comment]
@alboth we discussed that we will keep the "/" and don't make any changes to it.
The second problem described in the issue must be addressed. We need to clean up the breadcrumb template do only render aria-current="page" to one element.

**Review by benjaminkott — CHANGES_REQUESTED** [review]
We discussed to keep the "/" and accept that the screen reader reads them aloud.
We still need to tackle the second issue in the ticket and only render aria-current="page" once in the breadcrumb.

**Comment by benjaminkott** [comment]
@alboth as discussed we will to do this part of the requested changes

**Pull request closed without merging**
