### PR TITLE
[BUGFIX] Circumvent shortcut active state issue in HMENU

### PR DESCRIPTION
**Pull request by gilbertsoft**
Related: #750, https://forge.typo3.org/issues/85138
Resolves: #829

### CODE REVIEW

**Comment by benjaminkott** [comment]
@gilbertsoft would not circumvent the issue as it´s a core bug. should be fixed in core and not add the processor again in the bp.

**Comment by gilbertsoft** [comment]
> 
> 
> @gilbertsoft would not circumvent the issue as it´s a core bug. should be fixed in core and not add the processor again in the bp.

Have seen the closed PR? I'll have another look at the core issue, but I don't think Benni will allow a back port to 8.7. So this is finally meant for version not including the core fix. I'm absolutely with you but this seems better than the suggested fix in fluid

**Comment by gilbertsoft** [comment]
Created now two patches for the core to solve this issue:
- https://review.typo3.org/c/Packages/TYPO3.CMS/+/64569
- https://review.typo3.org/c/Packages/TYPO3.CMS/+/64570

**Comment by gilbertsoft** [comment]
Will close this one in favor of the core patche which hopefully goes into the next releases...

**Pull request closed without merging**
