### PR TITLE
[BUGFIX] fix for HTML5 markup validation

### PR DESCRIPTION
**Pull request by webian**
Please merge if ok, tnx!

### CODE REVIEW

**Comment by webian** [comment]
Hi @benjaminkott!
If I got what you say, you don't like the word "logo" after the sitetitle.
We know that alt attribute is used to describe the image expecially for screen reader or when the element cannot be rendered so I added the word "logo" to let user understand that it's in fact the logo of the website. Leaving only the site title did look a little misleading to me.

Btw, you're right saying to make it configurable, so I made it with the last commit.
Does it sound good? :)

**Comment by webian** [comment]
I thought about that (use a constant) but I think that only an advanced user (aka an administrator) will want to hack the value of the alt attribute of the logo.
So I think that it's better to not add another constant that could add more confusion to a normal user. Also the package remain more clean.
But if you think that a constant is necessary I will add, no problem!

**Comment by benjaminkott** [comment]
@webian if you want to change the logo you will anyways need to open the constant editor in most cases, if we just add it next to the logo path it should ne not a big deal.

**Comment by webian** [comment]
Hey @benjaminkott, what I mean is that probably a normal user won't be interested in edit an alt attribute.
But I agree that's not a big deal and I added a constant to overwrite the default alt text.
What do you think about it?

**Comment by benjaminkott** [comment]
@webian looks fine for me, will merge it move everything else into a followup
thx as always, hope youre at the devdays - ill owe u some beers already

**Comment by webian** [comment]
Tnx @benjaminkott 
well... I owe you many more! :)

**Pull request merged**
