### PR TITLE
[BUGFIX] Currently the content elements textpic and text media don't …

### PR DESCRIPTION
**Pull request by nothingbutnet**
…work properly.The gallery partial is used in text media and textpic elements, so it should be possible to only show one picture.

### CODE REVIEW

**Comment by benjaminkott** [comment]
hey @nothingbutnet, what TYPO3 Version you are using?

**Comment by nothingbutnet** [comment]
Hi @benjaminkott. I'm using 8.4.

**Comment by benjaminkott** [comment]
Please have a look here, https://github.com/benjaminkott/bootstrap_package/pull/388 its a TYPO3/Fluid bug, that will be resolved with TYPO3 8.5 no code changes needed.

https://github.com/TYPO3/Fluid/issues/190
https://github.com/TYPO3/Fluid/commit/52bf96a63e93c11f6f17bf8b7cc5a08c07fdf55f

**Comment by nothingbutnet** [comment]
Alright, then I'll close this one ...

**Pull request closed without merging**
