### PR TITLE
Add pages of type 'menu separator' as dropdown-header in the menu

### PR DESCRIPTION
**Pull request by fpoy**
Allow to have "menu separator" pages rendered as dropdown headers in the main navbar

### CODE REVIEW

**Comment by CDG47** [comment]
Thanks for your solution. It's really great and if it could be included in the next updates. It gonna be really useful to create a mega menu like Yamm.

**Comment by benjaminkott** [comment]
@fpoy hey, thx for the patch, i am unsure where you get the .isSpacer from? is something missing here?

**Comment by fpoy** [comment]
I don't know, perhaps it is a Typo3 v7.6-only feature ? I thought it was something widespread...
You can find it in :
- typo3/sysext/frontend/Classes/ContentObject/Menu/AbstractMenuContentObject.php
- typo3/sysext/frontend/Classes/ContentObject/Menu/GraphicalMenuContentObject.php
- typo3/sysext/frontend/Classes/ContentObject/Menu/TextMenuContentObject

I do not know how to detect that with older versions :(

**Comment by benjaminkott** [comment]
@fpoy thx for your patch, its now available in master branch. please see the commit for notes and adjustments

**Pull request closed without merging**
