### PR TITLE
RFC: Feature/add pdf thumbnails to imagerendering

### PR DESCRIPTION
**Pull request by pekue**
Using PDFs in Image / Text with Image does not render a thumbnail in the frontend. This is because file.type is 5 (document) in sys_file. I know that this proposal is not a good solution, because it doesn´t take $TYPO3_CONF_VARS['GFX']['imagefile_ext‘] into account, which it should - but it works.

### CODE REVIEW

**Comment by cedricziel** [comment]
Can you please rebase to the current master? Cheers.

**Comment by s-leger** [comment]
pdf are files of type 5, so current partials/media/type should also be changed according in order to be able to use them in frontend.
```
  <f:case value="5">
    <f:switch expression="{file_0.extension}">
      <f:case value="pdf">
        <f:render partial="Media/Image" arguments="{file: file, data: data, settings: settings}" />
      </f:case>
      <f:case default="TRUE">
        <div class="danger">File rendering for type:{file_0.type} {file_0.extension} is not supported.</div>
      </f:case>
    </f:switch>
  </f:case>
```

**Comment by benjaminkott** [comment]
while the change indeed sounds easy, it misses to check if ghostscript is properly installed. if ghostscript is not installed correctly it can lead to unwanted output in the frontend and it is hard to validate upfront.

**Comment by benjaminkott** [comment]
asked @lolli42 about this if we can make it somehow available during installation to check it before we render the page about this, until now i will close this pr - will provide a solution when we are able to ensure processing options are available.

**Pull request closed without merging**
