### PR TITLE
[FEATURE] add element wrap in lib.dynamicContent

### PR DESCRIPTION
**Pull request by Patta**
Now you can wrap each content element from lib.dynamicContent

For example to build a bootstrap grid:
`<f:cObject typoscriptObjectPath="lib.dynamicContent" data="{pageUid: '{data.uid}', colPos: '0', wrap: '<div class=\"row\">|</div>', elementWrap: '<div class=\"col-sm-4 col-md-3\">|</div>'}" />`

### CODE REVIEW

**Comment by benjaminkott** [comment]
@Patta sorry had problems to merge your pull request ive cherry-picked our path ant its now available in master. thx a lot!

https://github.com/benjaminkott/bootstrap_package/commit/4f93616d78b7d69f2a9bf6720f79114b6e12d607

**Comment by Patta** [comment]
@benjaminkott thanks, but it's not in v8.0.4

**Comment by benjaminkott** [comment]
@Patta 8.0.4 is a bugfix release, no new features will be merged in here. It will come with 8.1.0

**Comment by Patta** [comment]
@benjaminkott great thanks.

**Pull request closed without merging**
