### PR TITLE
Change JS for bootstrap 5 to vanilla JS

### LINKED ISSUE #1163: [FEATURE] Remove jQuery dependency if bootstrap 5 is selected
# Feature Request

Remove jQuery dependency if bootstrap 5 is selected

## Is your feature request related to a problem? Please describe

Since bootstrap 5 do not use jQuery anymore, the dependency should be removed from this package as well, if the user selects 
 version 5 of the framework.

## Describe the solution you'd like

Replace all JavaScripts coming with this package by vanilla JS versions. 

## Describe alternatives you've considered

I already developed replacements of this scripts and will create PR for it:

- bootstrap.navbar.js
- bootstrap.popover.js
- bootstrap.smoothscroll.js

Only bootstrap.accordion.js is left, but I think it is not needed for bootstrap 5. I removed it in a page where I used the accordion element and did not see any issues.

### PR DESCRIPTION
**Pull request by mediaessenz**
# Pull Request

## Related Issues

* Resolves #1163 

## Prerequisites

Rebuild JS by running `npm run js` inside Build folder.

## Description

- Change JS for bootstrap 5 to vanilla JS
- Remove jquery include from typoscript
- Rebuild js which updates modernizer.min.js as well

### CODE REVIEW

**Comment by gilbertsoft** [comment]
@mediaessenz not sure why you overwrite my fix again, now test is back red... So please revert your last commit and push it again.

**Comment by mediaessenz** [comment]
> @mediaessenz not sure why you overwrite my fix again, now test is back to red... So please revert your last commit and push it again.

I do not understand the problem, because I take your file, override my lokal (wrong) one and commit/pushed it again. I did this, because I would like to have the same state in my lokal system than the one in the forked version from where I made the pull request.

**Comment by mediaessenz** [comment]
> > > @mediaessenz not sure why you overwrite my fix again, now test is back to red... So please revert your last commit and push it again.
> > 
> > 
> > I do not understand the problem, because I take your file, override my lokal (wrong) one and commit/pushed it again. I did this, because I would like to have the same state in my lokal system than the one in the forked version from where I made the pull request.
> 
> You just had to pull after my push, that's all to have the same state...

Really?

I added the git repo from my forged version into my composer.json and required the "feature/1163-remove-query-dependency" branch.

**Comment by mediaessenz** [comment]
Sorry, closed accidentally

**Comment by mediaessenz** [comment]
reopen

**Comment by benjaminkott** [comment]
shit

**Comment by benjaminkott** [comment]
i made a huge mess trying to rebase the branch... so i cherry-picked the changes we need and made a new pull request. 
https://github.com/benjaminkott/bootstrap_package/pull/1212

closing this one - sorry!

**Pull request closed without merging**
