### PR TITLE
mainmenu: add css style 'active' for shortcut page pointing to parent

### PR DESCRIPTION
**Pull request by synac**

### CODE REVIEW

**Comment by synac** [comment]
Travis CI reports an issue with php 5.5. I checked it on a test server with php 5.5 and can't find any issues.

**Comment by benjaminkott** [comment]
@synac hey thx for your patch will look into this later, i think we should handle this in the menu processor to avoid complex conditions, travis should be fixed now btw

**Comment by gilbertsoft** [comment]
This will be solved directly in the core see https://forge.typo3.org/issues/85138

**Comment by benjaminkott** [comment]
@synac @gilbertsoft added new labels, and will close the pr for now - since this should be part of the core.

**Pull request closed without merging**
