### PR TITLE
[BUGFIX] Fixes #535

### LINKED ISSUE #535: Page cache disabled in conjunction with EXT:realurl
With a default, composer based, TYPO3 CMS 8.7.16, EXT:bootstrap_package 9.1.1 and EXT:realurl 2.2.1 we are experiencing caching issues (page cache disabled) - debugged with admin panel.

I have tracked down the issue to the following in [SYS][systemLog]:

```
26-06-18 13:11 - cms: $TSFE->set_no_cache() was triggered. Reason: Bad "L" parameter ("1") was detected by realurl. Page caching is disabled to prevent spreading of wrong "L" value.. Caching is disabled!
26-06-18 13:11 - cms: $TSFE->set_no_cache() was triggered. Reason: Bad "L" parameter ("2") was detected by realurl. Page caching is disabled to prevent spreading of wrong "L" value.. Caching is disabled!
```

The site is not configured with any extra languages, yet the bootstrap_package predefines to extra languages 1 & 2 in its TypoScript constants.

https://github.com/benjaminkott/bootstrap_package/blob/72e277cd24f4d05d2731f3281bb6ae28cc43a565/Configuration/TypoScript/constants.typoscript#L86

Should this not be changed to `languageValue = 0` so a default installation without any additional languages would work out of the box?

### PR DESCRIPTION
**Pull request by w3dev-dk**
Fixes #535

### Prerequisites

* [x] Changes have been tested on TYPO3 8.7 LTS
* [ ] Changes have been tested on TYPO3 dev-master
* [x] Changes have been tested on PHP 7.0.x
* [ ] Changes have been tested on PHP 7.1.x
* [ ] Changes have been tested on PHP 7.2.x
* [ ] Changes have been checked for CGL compliance `php-cs-fixer fix`

### Description

[Description of changes proposed in this pull request]

### Steps to Validate

1. [First Step]
2. [Second Step]
3. [and so on...]

### CODE REVIEW

**Comment by w3dev-dk** [comment]
NP. I´m just happy to help :)

**Comment by w3dev-dk** [comment]
I do not have the resources to make all the test as required in your *Prerequisites*. It´s honestly a small contribution (in the matter of line of code) and I hardly can imaging that it will break anything but it´s of cause up to you guys if that needs to be tested :)

**Comment by cedricziel** [comment]
@w3dev-dk everything's fine, don't worry. The change is simple enough to be accepted right away.

There's a few things to consider downstream, though. (The distribution needs to override the constant then, for example) And I don't have the resources to care about this now so I'll leave this up to Benjamin :)

But, there's nothing left to do for now - thank you for caring! :heart:

**Comment by benjaminkott** [comment]
@w3dev-dk @cedricziel thx guys, will take a look later - we still need to support the introduction package database on those versions - will investigate how we can solve this without sideeffects

**Comment by cedricziel** [comment]
That's exactly my concern

**Comment by w3dev-dk** [comment]
Oh, of cause, did not think about that 👍

**Comment by benjaminkott** [comment]
@w3dev-dk @cedricziel please see https://github.com/benjaminkott/bootstrap_package/issues/535. Sadly its too risky to do any changes here. The issue is already resolved in the master branch, since all configuration will now be done automaticly.

**Pull request closed without merging**
