### PR TITLE
RTE: Classes for links

### PR DESCRIPTION
**Pull request by SventB**
See https://github.com/benjaminkott/bootstrap_package/issues/281

### CODE REVIEW

**Comment by cedricziel** [comment]
Please use `git rebase -i HEAD~3` on the `master` branch.

Remove the two last lines mentioning `test1` and `revert` commit and save & close. Then force push to update the pull request.

Reason: The two commits added are useless.

**Comment by cedricziel** [comment]
Hey thanks for the adjustments :)

Please note that you could've updated the original pull request by rebasing like i mentioned. Pushes to the branch then require a force push.

You may want to read that part up in the git book, as it simplifies collaboration on github a lot as pull requests don't share state PLUS it will level you up with git *a lot*.

**Comment by SventB** [comment]
Yes, I have a lack in git knowledge ;) My TourtoiseGit didn't allow to rebase something.

**Comment by webian** [comment]
You could give a check to Smartgit @SventB 
http://www.syntevo.com/smartgit/

**Comment by cedricziel** [comment]
Use the shell, Sven. ;)

Jokes aside, TortoiseGit requires MSysGit, right? There should be a shell you can use. Along the lines there are also more adanced clients such as SourceTree (free) and SmartGit (free for OSS). I use SmartGit for repetitive tasks such as updating forks but I need the shell anyways for non-gui evironments.

**Comment by SventB** [comment]
Thanks for the useful hints.
I plan to contribute to this project more, I have a list about 20 improvements I'ld like to discuss and implement. I think I will have time for that in april and then I will have a closer look to GIT.

**Comment by cedricziel** [comment]
I see no use in creating knowledge silos; so please feel free to contact me about git if you need some advice. I'm not on the Slacks, but you can use the email address which is visible on my github user profile.

**Pull request closed without merging**
