### PR TITLE
Compatibility changes for TYPO3 v14.0

### PR DESCRIPTION
**Pull request by ohader**

### CODE REVIEW

**Comment by ohader** [comment]
`^13` tests would fail until https://review.typo3.org/c/Packages/TYPO3.CMS/+/86811 finally got released as v13 LTS release (Nov 12th, 2024)

**Comment by bnf** [comment]
Also see https://github.com/benjaminkott/bootstrap_package/pull/1528

**Comment by ohader** [comment]
> Also see #1528

I'm puzzled I did not spot that... 👀

**Comment by ohader** [comment]
Dropped in favor of #1528

**Pull request closed without merging**
