### PR TITLE
[TASK] Issues with RTE because of contentsCss

### LINKED ISSUE #930: Issues with RTE because of contentsCss
# Bug Report

## Prerequisites

* [x] Can you reproduce the problem on TYPO3 v9.5 LTS
* [x] Can you reproduce the problem on TYPO3 v10.4 LTS
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package)
  to see if your bug or enhancement is already reported?

## Description

I've found some issues and "hipcups" with the CSS which was used for ckeditor. 

1) Buttons are not clickable, the text can't be changed. To reproduce, click on third button and try to change the text:

rte_buttons

2) The default text size is pretty high: the text size is higher than the other texts in the TYPO3 BE or the buttons of the RTE (compare it to button "Normal").

rte_styles

## How to fix

Change the styles in EXT:bootstrap_package/Resources/Public/Css/bootstrapX-rte(.min).css.
I will provide a PR.

### PR DESCRIPTION
**Pull request by SventB**
# Pull Request

## Related Issues

* Fixes #930

## Prerequisites

* [x] Changes have been tested on TYPO3 v9.5 LTS
* [x] Changes have been tested on TYPO3 v10.4 LTS
* [x] Changes have been tested on PHP 7.2.x

## Description

See bug ticket.
I've set the font-size to 12px, that's the same of the TYPO3 backend.

### CODE REVIEW

**Review by gilbertsoft — CHANGES_REQUESTED** [review]
Same as before, the .css files are generated see https://github.com/benjaminkott/bootstrap_package/blob/master/Build/Gruntfile.js. Please change the correct sources and rebuild the .css. Thanks!

**Comment by SventB** [comment]
> Same as before, the .css files are generated see https://github.com/benjaminkott/bootstrap_package/blob/master/Build/Gruntfile.js. Please change the correct sources and rebuild the .css. Thanks!

@gilbertsoft Sorry, I didn't know these files were generated from LESS/SCSS.
I've changed the sources, but you should rebuild the .css because my rebuild with a LESS file watcher in PHPStorm produced too much differences.

**Comment by gilbertsoft** [comment]
> 
> 
> > Same as before, the .css files are generated see https://github.com/benjaminkott/bootstrap_package/blob/master/Build/Gruntfile.js. Please change the correct sources and rebuild the .css. Thanks!
> 
> @gilbertsoft Sorry, I didn't know these files were generated from LESS/SCSS.
> I've changed the sources, but you should rebuild the .css because my rebuild with a LESS file watcher in PHPStorm produced too much differences.

Mmh, how did you rebuild it? Normally you go to the Build folder and run `yarn build` which should do the whole job correctly....

**Comment by SventB** [comment]
I am using windows as OS.
Running `yarn build` results in

```
yarn run v1.22.10
$ ./node_modules/.bin/grunt build
Das System kann den angegebenen Pfad nicht finden.
error Command failed with exit code 1.
```

**Comment by gilbertsoft** [comment]
@SventB sorry for the delay. In the mean time I've rebase your patch and removed the font-size change, this is not a good idea because you destroy the sizes given by bootstrap. Sadly the change does not work for me, it's almost the same behaviour like before your patch. So this needs some work, maybe you are willing to continue here.

Little side note, we are not longer using yarn but npm. So run `npm run build` in the Build folder to recreate the CSS files.

**Comment by SventB** [comment]
@gilbertsoft 

> Sadly the change does not work for me, it's almost the same behaviour like before your patch

The important thing is to remove "user-select" or set it to "initial". Then you can select the button text. This issue only exists in Firefox.
I've made changes and tested it with bootstrap4-rte.min.css and bootstrap5-rte.min.css in Firefox and Chrome.

**Pull request closed without merging**
