### PR TITLE
Carousel header should not be required

### PR DESCRIPTION
**Pull request by phvt**
The carousel header field should behave like tt_content.header, which is not a required field.

### CODE REVIEW

**Comment by phvt** [comment]
This is incomplete -- I'm working on changes to Partials/ContentElements/Carousel/* so that empty header tags are not rendered.

**Comment by webian** [comment]
Hi @phvt,
please also check conversation in https://github.com/benjaminkott/bootstrap_package/pull/140 about carousel header not required.

**Comment by phvt** [comment]
Thanks @webian,

What if the layout for the carousel header could be set to Hidden (not rendered), as with tt_content.header_layout?

**Comment by webian** [comment]
Sounds good to me but you should also ask to @benjaminkott.
( If you don't know we have a Slack channel dedicated to EXT:bootstrap-package: https://typo3.slack.com/messages/bootstrap-package/ )

**Comment by benjaminkott** [comment]
@phvt if i get this correctly you want to have a variant where you only put out an image and the textfield without the header, is this correct?

**Comment by benjaminkott** [comment]
with https://github.com/benjaminkott/bootstrap_package/commit/e85c213ff8ef6545130db231b7bcfa7cda2a8011 and the introduction of automatic lookup of templates https://github.com/benjaminkott/bootstrap_package/commit/42a676dbc781dc3deb47ef00fb9e1ba12d5fd537 the carousel should be flexible enough to handle custom types if nessesary.

**Pull request closed without merging**
